### ISSUE TITLE
time.clock() removed from Python 3.8

### ISSUE THREAD

**Issue by w0rldpain** [nlitsme/vimdecrypt#2]
Per the Python 3.8 [documentation](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals):
> The function `time.clock()` has been removed, after having been deprecated since Python 3.3: use [`time.perf_counter()`](https://docs.python.org/3/library/time.html#time.perf_counter) or [`time.process_time()`](https://docs.python.org/3/library/time.html#time.process_time) instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in [bpo-36895](https://bugs.python.org/issue36895).)

I pulled @jarp01's downstream [fork](https://github.com/jarp01/vimdecrypt) (which uses `time.perf_counter()` instead), and tested it against a file for an ongoing CTF -- it works perfectly. (That said, the program kept running through the dict file I fed it after finding the password and extracting the flag, and I had to kill it with Ctrl-C -- is that intentional behavior?)

**Comment by nlitsme** [comment]
thanks for pointing this out.  now fixed in my latest commit.

**Comment by w0rldpain** [comment]
Can confirm your latest commit works as expected. Thanks!
